name: Build And Run Java
#events
on:
  push:
    branches:
      - main
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #clone repo to run operation
      - name: Set up
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build # B
        run: cd src && javac Main.java
        shell: bash

      - name: Run
        run: cd src && java Main
        shell: bash   
     - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: ${{ secrets.SMTP_SERVER }} # smtp.gmail.com
          smtp-port: ${{ secrets.SMTP_PORT }} # 465
          smtp-secure: true
          from-email: ${{ secrets.EMAIL_USER }}
          to-email: fullstackltd@gmail.com
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>